CREATE TABLE SYS_USER(ID INT PRIMARY KEY AUTO_INCREMENT, USERNAME VARCHAR(255),PASSWORD VARCHAR (255),ROLE VARCHAR (255));
INSERT INTO SYS_USER VALUES(1, 'admin','$2a$10$OklTeMgRgIjgjPjOFz7p8e8LzUI7z1B3XpcTvb.skYUeeDnEpoNjS','system');
INSERT INTO SYS_USER VALUES(2, 'teacher','$2a$10$OklTeMgRgIjgjPjOFz7p8e8LzUI7z1B3XpcTvb.skYUeeDnEpoNjS','teacher');
INSERT INTO SYS_USER VALUES(3, 'stu1','$2a$10$OklTeMgRgIjgjPjOFz7p8e8LzUI7z1B3XpcTvb.skYUeeDnEpoNjS','student');
INSERT INTO SYS_USER VALUES(4, 'stu2','$2a$10$OklTeMgRgIjgjPjOFz7p8e8LzUI7z1B3XpcTvb.skYUeeDnEpoNjS','student');

CREATE TABLE COURSE(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255),CONTENT VARCHAR(500), ORDERNUMS INT, STATUS VARCHAR(1) );
INSERT INTO COURSE VALUES(1,'语文','少年闰土',0,'1');
INSERT INTO COURSE VALUES(2,'数学','f(x)=1',0,'1');
INSERT INTO COURSE VALUES(3,'英语','Hello Word',0,'1');

CREATE TABLE COURSE_ORDER(ID INT PRIMARY KEY AUTO_INCREMENT, USER_ID INTEGER,COURSE_ID INTEGER, STATUS VARCHAR(1) );
